gt4_e_interface_homepage:
    path:     /
    defaults: { _controller: GT4EInterfaceBundle:Default:index }

gt4_e_interface_ressources:
    path:     /login
    defaults: { _controller: GT4EInterfaceBundle:Default:login }
