gt4_e_interface_homepage:
    path:     /
    defaults: { _controller: GT4EInterfaceBundle:Default:index }

gt4_e_interface_login:
    path:     /login
    defaults: { _controller: GT4EInterfaceBundle:Default:login }

gt4_e_interface_admin:
    path:     /admin
    defaults: { _controller: GT4EInterfaceBundle:Default:admin }

gt4_e_interface_adminGetClient:
    path:     /admin/getClient
    defaults: { _controller: GT4EInterfaceBundle:Default:getClient }
    methods:  [POST]

gt4_e_interface_adminUpdateClient:
    path:     /admin/updateClient
    defaults: { _controller: GT4EInterfaceBundle:Default:updateClient }
    methods:  [POST]

gt4_e_interface_adminCreateClient:
    path:     /admin/createClient
    defaults: { _controller: GT4EInterfaceBundle:Default:createClient }
    methods:  [POST]

gt4_e_interface_adminaddFaqt:
    path:     /admin/addFaq
    defaults: { _controller: GT4EInterfaceBundle:Default:addFaq }
    methods:  [POST]

gt4_e_interface_admingetAllClients:
    path:     /admin/getAllClients
    defaults: { _controller: GT4EInterfaceBundle:Default:getAllClients }
    methods:  [POST]
