<?php

namespace AppBundle\Repository;

/**
 * PossederRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PossederRepository extends \Doctrine\ORM\EntityRepository
{
}
