<?php

namespace AppBundle\Repository;

/**
 * UilisateurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UilisateurRepository extends \Doctrine\ORM\EntityRepository
{
}
